let names = [
    "Karol",
    "Martina",
    "Robert",
    "Rene"
];
// WRITE A FUNCTION THAT TAKES ARRAY WITH NAMES AS ARGUMENT AND RETURNS COPY OF THAT ARRAY WITH NAMES IN UPPERCASE FORMAT, FOR EXAMPLE ["KAROL", "MARTINA", "ROBERT", "RENE"]

// WRITE A FUNCTION THAT FIND THE LONGEST NAME IN ARRAY WITH REDUCE FUNCTION

// WRITE A FUNCTION THAT FILTERS THE NAMES HAVING SOME LETTER PROVIDED AS ARGUMENT

let students = [
    { name:"Karol", examResult:4 },
    { name:"John", examResult:3 },
    { name:"Sophie", examResult:2 },
    { name:"Robert", examResult:5 },
    { name:"Bruce", examResult:1 }
]

// WRITE A FUNCTION TAKING TWO ARGUMENTS (ARRAY WITH NAMES, SEARCHED NAME), AND RETURNS THE EXAM RESULT OF SEARCHED PERSON 
// FOR EXAMPLE getExamResult(students,"Karol") SHOULD RETURN 4